"""add_clip_hashtags

Revision ID: 3875333f2905
Revises: 5287abbdb094
Create Date: 2026-05-02 22:59:51.698818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3875333f2905'
down_revision: Union[str, None] = '5287abbdb094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('hashtags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'hashtags')
    # ### end Alembic commands ###
