"""add_liked_disliked_to_clips

Revision ID: 5287abbdb094
Revises: 87e3bbce0b47
Create Date: 2026-05-02 18:20:03.906587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5287abbdb094'
down_revision: Union[str, None] = '87e3bbce0b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('liked', sa.Boolean(), nullable=False))
    op.add_column('clips', sa.Column('disliked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'disliked')
    op.drop_column('clips', 'liked')
    # ### end Alembic commands ###
