"""brand_templates

Revision ID: 87e3bbce0b47
Revises: 101374935308
Create Date: 2026-05-02 16:04:34.561830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87e3bbce0b47'
down_revision: Union[str, None] = '101374935308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('font_path', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=32), nullable=False),
    sa.Column('secondary_color', sa.String(length=32), nullable=False),
    sa.Column('caption_style', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('intro_clip_path', sa.Text(), nullable=True),
    sa.Column('outro_clip_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_templates')
    # ### end Alembic commands ###
